server:
  port: 8005
  application:
    name: service-msm

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 123
  redis:
    lettuce:
      pool:
        max-idle: '5'
        max-active: '20'
        min-idle: '0'
        max-wait: '-1'
    database: '0'
    host: 127.0.0.1
    port: '6379'
    timeout: '1800000'
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/zhangmingge/cmsservice/mapper/xml/*.xml

aliyun:
  msm:
    keyid: LTAI5tJYqqAWSH4LvaaZFDB8
    keysecret: 5GEkmK6a7Ghfcu961srvO9QblMdnzU
    SignName: 阿里云短信测试
    TemplateCode: SMS_154950909